#!/usr/bin/env python3

import sys

from PyQt5.QtWidgets import QApplication
from Views.login_view import LoginWindow

if __name__ == '__main__':
    app = QApplication(sys.argv)
    loginPage = LoginWindow()
    loginPage.show()
    app.exec_()
